---
- name: To declare variables
  hosts: all
  remote_user: ansiuser
  become: true
  vars:
   users:
   - auser1
   - auser2
   - auser3
  tasks: 
  - name: To create users on the clients.
    user: name={{ item }} state=present 
    with_items: "{{ users }}"
