---
- name: First play.
  hosts: all
  remote_user: ansible
  become: true
  tasks:
  - name: To check the bash version.
    replace: 
      path: /bin/myscript.sh 
      regexp: Bash 
      replace: bash
      backup: yes
  - name: Command.
    command: "/bin/myscript.sh"
    register: output 
  - name: To display the command output.
    #To filter the data from the registered output.
    debug: var=output.stdout
