---
- name: To declare variables
  hosts: all
  remote_user: ansiuser
  become: true
  vars:
   users: 
    - auser54
    - auser22
    - auser33
  tasks: 
  - name: To create users on the clients.
    user: name={{ item }} state=present 
    with_items: "{{ users }}"
