---
- hosts: all
  remote_user: ansiuser
  become: true
  vars_files:
  - /home/ansiuser/Ansible/file.yml
  tasks: 
  - name: To create files.
    file: path=/var/tmp/{{ item }}  state=touch
    with_items: "{{ var1 }}" 
  - name: To Create users from the vars referencing files.
    user: name={{ item }}
    with_items: "{{ var2 }}"
