---
- hosts: all
  remote_user: ansiuser
  become: true
  gather_facts: no 
  tasks:
  - name: To create custom fact location.
    file: path=/etc/ansible/facts.d state=directory force=yes
  - name: To copy the custom factor file to nodes.
    copy: src=custom2.fact dest=/etc/ansible/facts.d/ mode=0755
