---
- hosts: all 
  remote_user: ansiuser
  #sudo: yes
  become: true
  vars: 
   users:
     - myuser1 
     - myuser2 
     - myuser3 
   packages:
     - httpd
     - mariadb
     - screen
  tasks:
  - name: To create User. 
    user: name={{ users[0] }} state=present
    when: ( ansible_host in "172.31.22.217" )
  - name: To install the mariadb. 
    user: name={{ packages[0] }} state=present
    when: ( ansible_host in "172.31.22.217" )
  - name: To create User. 
    user: name={{ users[1] }} state=present
    when: ( ansible_host in "172.31.22.217" )
  - name: To install the mariadb. 
    user: name={{ packages[1] }} state=present
    when: ( ansible_host in "172.31.22.217" )
    #with_items: "{{ users }}"
    #when: ( 'myuser1' in users ) 
    #register: value
    #notify: restart the service
    tags: DB
  - debug: var=value
  #handlers: 
  #- name: restart the service
    #service: name=mariadb-server state=restarted enabled=true 
    #service: name=httpd state=restarted enabled=true
