---
- hosts: all
  remote_user: ansiuser
  become: true
  gather_facts: no
  tasks: 
  - name: To install the package.
    yum: name=httpd state=latest
    when: inventory_hostname in groups['WEB']
  - name: To install the db server.
    yum: name=mariadb state=latest
    when: inventory_hostname in groups['DB']
