---
- name: To perform the iteration.
  hosts: all
  remote_user: ansiuser
  become: true
  vars: 
   users:
   - user1
   - user2
   - user3
   files:
   - file1
   - file2
   - file3
  tasks:
  - name: To Create4 users.
    user: name={{ item }} state=present
    with_items: "{{ users }}"
    register: exit_status 
  - name: to see the result or command status.
    debug: var=exit_status 
  - name: To create files.
    file: path=/var/tmp/{{item}} state=touch
    with_items: "{{ files }}"
